
# sites to crawl
entryPoint:
- http://www.thaiunion.com
- http://www.minor.com
- http://www.indoramaventures.com


# max depth for crawler to follow
maxDepth: 3

# max worker
parallelism: 5

# random delay (second)
delay: 2


# path to store data scraped data from crawler
dataPath: "data/crawl"

# path to store indexed data
indexPath: "data/index"


# http address, 0.0.0.0:8080 or :8080, it means listening all ipv4 address in local machine
httpAddress: ":8080"