
# sites to crawl
entryPoint:
#- www.thaiunion.com
#- www.minor.com
#- www.indoramaventures.com
- http://www.indoramaventures.com/th/our-products/packaging


# max depth for crawler to follow
maxDepth: 1

# max worker
parallelism: 1

# random delay (second)
delay: 2