
# sites to crawl
entryPoint:
#- http://www.thaiunion.com
- http://www.minor.com
#- http://www.indoramaventures.com


# max depth for crawler to follow
maxDepth: 3

# max worker
parallelism: 2

# random delay (second)
delay: 2


# path to store data scraped data from crawler
crawlerDataPath: "data/crawler"

# path to store index data
indexDataPath: "data/index"